
Feature: Program Monitoring
  As an admin
  I want to monitor program statistics
  So that I can analyze program popularity, revenue, attendance, and progress

  Scenario: View statistics on the most popular programs by enrollment
    Given the system has program enrollment data
    When I request the most popular programs
    Then I should see a list of programs sorted by enrollment count in descending order
    And the total number of enrollments for each program should be displayed

  Scenario: Generate reports on revenue
    Given the system has revenue data for programs
    When I generate a revenue report
    Then I should see the revenue generated by each program
    And the total revenue across all programs should be displayed

  Scenario: Generate reports on attendance
    Given the system tracks attendance for all programs
    When I generate an attendance report
    Then I should see the total attendance for each program
    And the average attendance percentage across all programs should be displayed

  Scenario: Generate reports on client progress
    Given the system tracks client progress in programs
    When I generate a client progress report
    Then I should see individual client progress for each program
    And a summary of overall progress statistics should be displayed

  Scenario: Track active and completed programs
    Given the system tracks program statuses
    When I view the list of programs
    Then I should see separate lists for active and completed programs
    And the total number of active and completed programs should be displayed
